[build]
builder = "DOCKERFILE"
dockerfilePath = "Backend/Dockerfile.prod"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
SPRING_PROFILES_ACTIVE = "prod" 